workflows:
  my-workflow:
    name: Vorspill
    labels:
      - QA
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - vors
      vars:
        PUBLIC_ENV_VAR: "vors"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    intergtations:
      app_store_connect: codemagicapikry
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      app_store_connect:
        auth: intergration
        # submit_to_testflight: false
        submit_to_app_store: true
      email:
        recipients:
          - luddetv@gmail.com
      scripts:
        - echo 'Post-publish script'
