workflows:
  ios-app:
    name: Vorspill
    environment:
      xcode: latest
      vars:
        XCODE_WORKSPACE: "vorspill.xcworkspace"
        XCODE_SCHEME: "vorspill"
        XCODE_PROJECT: "vorspill.xcodeproj"  # This line can be removed if you're using a workspace

    instance_type: mac_mini_m1
    

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true

    scripts:
      - name: Install dependencies
        script: |
          echo "Installing CocoaPods"
          pod install
      - name: Build ipa for distribution
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release build CODE_SIGN_IDENTITY="iPhone Distribution" PROVISIONING_PROFILE="xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

    publishing:
      app_store_connect:
        apple_id: luddetv@gmail.com
        # password: @env:APP_SPECIFIC_PASSWORD  # Ensure you have set this in your environment variables on CodeMagic
        app_identifier: "no.vorspill"
        submit_to_app_store: true
        release_type: SCHEDULED
        # scheduled_release_date: "2023-05-01T14:00:00Z" # Uncomment and set this if needed
