workflows:
  capacitor-build:
    name: Nuxt3 + Capacitor App
    environment:
      vars:
        # Define any environment variables needed
      node: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm install
      - name: Build Nuxt3 Project
        script: |
          npm run build
      - name: Add Capacitor Platforms
        script: |
          npx cap add android
          npx cap add ios
      - name: Copy Web Assets to Capacitor
        script: |
          npx cap copy
      - name: Build iOS and Android
        script: |
          npx cap open ios
          npx cap open android
    artifacts:
      - android/app/build/outputs/**/*.apk
      - ios/DerivedData/**/Build/Products/**/*.ipa
    # Define triggers, caching, publishing options as needed
